// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

function resolveDatabaseUrl() {
  const raw = process.env["DATABASE_URL"] ?? "";
  if (raw.startsWith("prisma+postgres://")) {
    const apiKey = raw.split("api_key=")[1];
    const decoded = JSON.parse(Buffer.from(apiKey, "base64").toString());
    return decoded as { databaseUrl: string; shadowDatabaseUrl: string };
  }
  return { databaseUrl: raw, shadowDatabaseUrl: undefined };
}

const { databaseUrl, shadowDatabaseUrl } = resolveDatabaseUrl();

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
    shadowDatabaseUrl,
  },
});
